// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyonehjosofmqbnjumce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5b25laGpvc29mbXFibmp1bWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODY1ODksImV4cCI6MjA1OTQ2MjU4OX0.gYNel8VopCZzTmJd7wXmtlhfA20qA1Gs1R-dlTEZA78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);